const Facultydata = [
    {
        id : 1,
        image : "./images/profimages/ghosh.jpg",
        name : "   Abhijit Ghosh  ",
        link : "demo",
    },
    {
        id : 2,
        image : "./images/profimages/prof20.jpeg",
        name : " Ajay Kumar Kushwaha",
        link : "P5",
    },
    {
        id : 3,
        image : "./images/profimages/prof1.jpg",
        name : " Chandan Halder",
        link : "P2",
    },
    {
        id : 4,
        image : "./images/profimages/dkrai.jpg",
        name : " Dhirendra Kumar Rai",
        link : "P3",
    },
    {
        id : 5,
        image : "./images/profimages/basha.jpg",
        name : " Dudekula Althaf Basha",
        link : "P1",
    },
    {
        id : 6,
        image : "./images/profimages/prof6.jpg",
        name : " Eswara Prasad Korimilli",
        link : "P4",
    },
    {
        id : 7,
        image : "./images/profimages/hemanth.jpg",
        name : " Hemant Borkar",
        link : "P6",
    },
    {
        id : 8,
        image : "./images/profimages/muru.jpg",
        name : " Jayaprakash Murugesan",
        link : "P7",
    },
    {
        id : 9,
        image : "./images/profimages/kd.jpg",
        name : " Khushubo Devi",
        link : "P8",
    },
    {
        id : 10,
        image : "./images/profimages/prof11.jpg",
        name : " Mrigendra Dubey",
        link : "P9",
    },
    {
        id : 11,
        image : "./images/profimages/nissi.jpg",
        name : " Nisheeth Kumar Prasad",
        link : "P10",
    },
    {
        id : 12,
        image : "./images/profimages/shirage.jpg",
        name : " Parasharam M. Shirage",
        link : "P11",
    },
    {
        id : 13,
        image : "./images/profimages/rsm.jpg",
        name : " Ram Sajeevan Maurya",
        link : "P12",
    },
    {
        id : 14,
        image : "./images/profimages/ran.jpg",
        name : " Ranjith Kumar Poobalan",
        link : "P13",
    },
    {
        id : 15,
        image : "./images/profimages/prof2.jpg",
        name : " Rupesh Devan",
        link : "P14",
    },
    {
        id : 16,
        image : "./images/profimages/prof4.png",
        name : " Santosh Hosmani",
        link : "P15",
    },
    {
        id : 17,
        image : "./images/profimages/prof6.jpg",
        name : " Sumanta Samal",
        link : "P16",
    },
    {
        id : 17,
        image : "./images/profimages/prof13.jpg",
        name : "  Sunil Kumar",
        link : "P16",
    },
    {
        id : 18,
        image : "./images/profimages/prof18.jpg",
        name : " Venkata Vamsi Koruprolu",
        link : "P17",
    },
    {
        id : 19,
        image : "./images/profimages/vinod.jpg",
        name : " Vinod Kumar",
        link : "P18",
    },
    {
        id : 20,
        image : "./images/profimages/samal.jpg",
        name : " Sumanta Samal",
        link : "demo",
    },
]
export default Facultydata